-- 1 에서  55  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글1','수고하셨습니다.',1,to_date('2023-01-21', 'RRRR-MM-DD'),NULL,NULL,0);
--행 2
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글2','감사합니다.',2,to_date('2023-01-22', 'RRRR-MM-DD'),NULL,NULL,0);
--행 3
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글3','수고하셨습니다.',3,to_date('2023-01-23', 'RRRR-MM-DD'),NULL,NULL,0);
--행 4
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글4','감사합니다.',4,to_date('2023-01-24', 'RRRR-MM-DD'),NULL,NULL,0);
--행 5
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글5','수고하셨습니다.',5,to_date('2023-01-25', 'RRRR-MM-DD'),NULL,NULL,0);
--행 6
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글6','감사합니다.',6,to_date('2023-01-26', 'RRRR-MM-DD'),NULL,NULL,0);
--행 7
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글7','수고하셨습니다.',7,to_date('2023-01-27', 'RRRR-MM-DD'),NULL,NULL,0);
--행 8
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글8','감사합니다.',8,to_date('2023-01-28', 'RRRR-MM-DD'),NULL,NULL,0);
--행 9
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글9','수고하셨습니다.',9,to_date('2023-01-29', 'RRRR-MM-DD'),NULL,NULL,0);
--행 10
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글10','감사합니다.',10,to_date('2023-01-30', 'RRRR-MM-DD'),NULL,NULL,0);
--행 11
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글11','수고하셨습니다.',11,to_date('2023-01-31', 'RRRR-MM-DD'),NULL,NULL,0);
--행 12
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글12','감사합니다.',12,to_date('2023-02-01', 'RRRR-MM-DD'),NULL,NULL,0);
--행 13
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글13','수고하셨습니다.',13,to_date('2023-02-02', 'RRRR-MM-DD'),NULL,NULL,0);
--행 14
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글14','감사합니다.',14,to_date('2023-02-03', 'RRRR-MM-DD'),NULL,NULL,0);
--행 15
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글15','수고하셨습니다.',15,to_date('2023-02-04', 'RRRR-MM-DD'),NULL,NULL,0);
--행 16
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글16','감사합니다.',16,to_date('2023-02-05', 'RRRR-MM-DD'),NULL,NULL,0);
--행 17
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글17','수고하셨습니다.',17,to_date('2023-02-06', 'RRRR-MM-DD'),NULL,NULL,0);
--행 18
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글18','감사합니다.',18,to_date('2023-02-07', 'RRRR-MM-DD'),NULL,NULL,0);
--행 19
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글19','수고하셨습니다.',19,to_date('2023-02-08', 'RRRR-MM-DD'),NULL,NULL,0);
--행 20
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글20','감사합니다.',20,to_date('2023-02-09', 'RRRR-MM-DD'),NULL,NULL,0);
--행 21
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글21','수고하셨습니다.',21,to_date('2023-02-10', 'RRRR-MM-DD'),NULL,NULL,0);
--행 22
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글22','감사합니다.',22,to_date('2023-02-11', 'RRRR-MM-DD'),NULL,NULL,0);
--행 23
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글23','수고하셨습니다.',23,to_date('2023-02-12', 'RRRR-MM-DD'),NULL,NULL,0);
--행 24
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글24','감사합니다.',24,to_date('2023-02-13', 'RRRR-MM-DD'),NULL,NULL,0);
--행 25
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글25','수고하셨습니다.',25,to_date('2023-02-14', 'RRRR-MM-DD'),NULL,NULL,0);
--행 26
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글26','감사합니다.',26,to_date('2023-02-15', 'RRRR-MM-DD'),NULL,NULL,0);
--행 27
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글27','수고하셨습니다.',27,to_date('2023-02-16', 'RRRR-MM-DD'),NULL,NULL,0);
--행 28
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글28','감사합니다.',28,to_date('2023-02-17', 'RRRR-MM-DD'),NULL,NULL,0);
--행 29
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글29','수고하셨습니다.',29,to_date('2023-02-18', 'RRRR-MM-DD'),NULL,NULL,0);
--행 30
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글30','감사합니다.',30,to_date('2023-02-19', 'RRRR-MM-DD'),NULL,NULL,0);
--행 31
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글31','수고하셨습니다.',31,to_date('2023-02-20', 'RRRR-MM-DD'),NULL,NULL,0);
--행 32
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글32','감사합니다.',32,to_date('2023-02-21', 'RRRR-MM-DD'),NULL,NULL,0);
--행 33
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글33','수고하셨습니다.',33,to_date('2023-02-22', 'RRRR-MM-DD'),NULL,NULL,0);
--행 34
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글34','감사합니다.',34,to_date('2023-02-23', 'RRRR-MM-DD'),NULL,NULL,0);
--행 35
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글35','수고하셨습니다.',35,to_date('2023-02-24', 'RRRR-MM-DD'),NULL,NULL,0);
--행 36
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글36','감사합니다.',36,to_date('2023-02-25', 'RRRR-MM-DD'),NULL,NULL,0);
--행 37
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글37','수고하셨습니다.',37,to_date('2023-02-26', 'RRRR-MM-DD'),NULL,NULL,0);
--행 38
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글38','감사합니다.',38,to_date('2023-02-27', 'RRRR-MM-DD'),NULL,NULL,0);
--행 39
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글39','수고하셨습니다.',39,to_date('2023-02-28', 'RRRR-MM-DD'),NULL,NULL,0);
--행 40
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글40','감사합니다.',40,to_date('2023-03-01', 'RRRR-MM-DD'),NULL,NULL,0);
--행 41
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글41','수고하셨습니다.',41,to_date('2023-03-02', 'RRRR-MM-DD'),NULL,NULL,0);
--행 42
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글42','감사합니다.',42,to_date('2023-03-03', 'RRRR-MM-DD'),NULL,NULL,0);
--행 43
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글43','수고하셨습니다.',43,to_date('2023-03-04', 'RRRR-MM-DD'),NULL,NULL,0);
--행 44
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글44','감사합니다.',44,to_date('2023-03-05', 'RRRR-MM-DD'),NULL,NULL,0);
--행 45
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글45','수고하셨습니다.',45,to_date('2023-03-06', 'RRRR-MM-DD'),NULL,NULL,0);
--행 46
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글46','감사합니다.',46,to_date('2023-03-07', 'RRRR-MM-DD'),NULL,NULL,0);
--행 47
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글47','수고하셨습니다.',47,to_date('2023-03-08', 'RRRR-MM-DD'),NULL,NULL,0);
--행 48
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글48','감사합니다.',48,to_date('2023-03-09', 'RRRR-MM-DD'),NULL,NULL,0);
--행 49
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글49','수고하셨습니다.',49,to_date('2023-03-10', 'RRRR-MM-DD'),NULL,NULL,0);
--행 50
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글50','감사합니다.',50,to_date('2023-03-11', 'RRRR-MM-DD'),NULL,NULL,0);
--행 51
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글51','수고하셨습니다.',51,to_date('2023-03-12', 'RRRR-MM-DD'),NULL,NULL,0);
--행 52
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글52','감사합니다.',52,to_date('2023-03-13', 'RRRR-MM-DD'),NULL,NULL,0);
--행 53
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글53','수고하셨습니다.',53,to_date('2023-03-14', 'RRRR-MM-DD'),NULL,NULL,0);
--행 54
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글54','감사합니다.',54,to_date('2023-03-15', 'RRRR-MM-DD'),NULL,NULL,0);
--행 55
INSERT INTO REVIEW (REVIEW_NO, REVIEW_NAME, REVIEW_CONTENT, REVIEW_AUTHOR, REVIEW_INSERT, REVIEW_UPDATE, REVIEW_DELETE, REVIEW_VIEW) VALUES (SEQ_REVIEW.NEXTVAL,'이용후기글55','수고하셨습니다.',55,to_date('2023-03-16', 'RRRR-MM-DD'),NULL,NULL,0);

COMMIT;