DROP TABLE PAYMENT;

CREATE TABLE PAYMENT (
	PAYMENT_NO	NUMBER		NOT NULL PRIMARY KEY,
	PAYMENT_TID	VARCHAR2(80)	NOT NULL,
	PAYMENT_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PAYMENT_CANCEL	DATE NULL,
	PAYMENT_RESERVATION_NO	NUMBER		NOT NULL
);

DROP SEQUENCE SEQ_PAYMENT;

CREATE SEQUENCE SEQ_PAYMENT NOCYCLE;