DROP TABLE ATTACHMENT;
DROP SEQUENCE SEQ_ATTACHMENT;

CREATE TABLE ATTACHMENT (
	ATTACHMENT_NO	NUMBER		NOT NULL PRIMARY KEY,
	ATTACHMENT_BOARD_NO	NUMBER	NOT NULL,
    ATTACHMENT_ORIGIN_NAME VARCHAR2(255) NOT NULL,
    ATTACHMENT_CHANGE_NAME VARCHAR2(255) NOT NULL,
	ATTACHMENT_FILE_PATH	VARCHAR2(400) NULL,
	ATTACHMENT_UPLOAD_DATE	DATE DEFAULT SYSDATE NOT NULL,
    ATTACHMENT_STATUS VARCHAR2(1) DEFAULT 'Y' NULL,
    FOREIGN KEY (ATTACHMENT_BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

CREATE SEQUENCE SEQ_ATTACHMENT NOCYCLE;

COMMIT;