DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_COMMENTS;
DROP SEQUENCE SEQ_CONSULTING;
DROP SEQUENCE SEQ_FILES;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_REVIEW;

CREATE SEQUENCE SEQ_BOARD NOCYCLE;
CREATE SEQUENCE SEQ_COMMENTS NOCYCLE;
CREATE SEQUENCE SEQ_CONSULTING NOCYCLE;
CREATE SEQUENCE SEQ_FILES NOCYCLE;
CREATE SEQUENCE SEQ_LIKES NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW NOCYCLE;

COMMIT;