DROP TABLE PAYMENT;

CREATE TABLE PAYMENT (
	PAYMENT_NO	NUMBER		NOT NULL PRIMARY KEY,
	PAYMENT_TID	VARCHAR2(80)	NOT NULL,
    PAYMENT_AID VARCHAR2(80) NULL,
    PAYMENT_METHOD VARCHAR2(30) NULL,
	PAYMENT_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PAYMENT_CANCEL	DATE NULL,
    PAYMENT_APPROVED VARCHAR2(30) NULL,
	PAYMENT_RESERVATION_NO	NUMBER		NOT NULL,
    PAYMENT_USER_NO NUMBER NOT NULL,
    PAYMENT_STATUS_CODE NUMBER DEFAULT 0 NOT NULL
);

DROP SEQUENCE SEQ_PAYMENT;

CREATE SEQUENCE SEQ_PAYMENT NOCYCLE;

COMMIT;