DROP TABLE FILES;
DROP TABLE COMMENTS;
DROP TABLE CONSULTING;
DROP TABLE LIKES;
DROP TABLE REVIEW;
DROP TABLE MEMBER;
DROP TABLE BOARD;

CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(40) NOT NULL UNIQUE,
	MEMBER_PWD	VARCHAR2(80) NOT NULL,
	MEMBER_NAME	VARCHAR2(40) NOT NULL,
	MEMBER_PHONE VARCHAR2(16) NOT NULL UNIQUE,
	MEMBER_EMAIL	VARCHAR2(40)		NOT NULL UNIQUE,
	MEMBER_ADDRESS	VARCHAR2(200)		NOT NULL,
    MEMBER_ADDRESS_DETAIL	VARCHAR2(200)		NOT NULL,
    MEMBER_BIRTH	DATE NOT NULL,
    MEMBER_DESCRIPTION	VARCHAR2(2000)		NULL,
	MEMBER_JOIN	DATE	DEFAULT SYSDATE	NOT NULL,
	MEMBER_LEAVE	DATE		NULL,
    MEMBER_STATUS NUMBER DEFAULT 1 CHECK(MEMBER_STATUS IN (0, 1)) NOT NULL,
    MEMBER_LEAVE_REASON VARCHAR2(100) NULL,
    MEMBER_ADMIN NUMBER DEFAULT 0 CHECK(MEMBER_ADMIN IN (0,1)) NOT NULL
);

CREATE TABLE REVIEW(
	REVIEW_NO	NUMBER PRIMARY KEY,
	REVIEW_NAME	VARCHAR2(100)	DEFAULT '이름없는 게시글'	NOT NULL,
	REVIEW_CONTENT	VARCHAR2(4000)		NULL,
    REVIEW_AUTHOR	NUMBER NOT NULL,
	REVIEW_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	REVIEW_UPDATE	DATE		NULL,
	REVIEW_DELETE	DATE		NULL,
	REVIEW_VIEW	NUMBER	DEFAULT 0	NOT NULL,
	REVIEW_IP	VARCHAR2(40)		NULL,
    FOREIGN KEY (REVIEW_AUTHOR) REFERENCES MEMBER(MEMBER_NO)
);

CREATE TABLE FILES(
	FILES_NO	NUMBER PRIMARY KEY,
    FILES_REVIEW_NO NUMBER NOT NULL,
	FILES_ORIGIN_NAME	VARCHAR2(80)		NOT NULL,
	FILES_CHANGE_NAME	VARCHAR2(80)		NOT NULL UNIQUE,
	FILES_PATH	VARCHAR2(40)		NULL,
	FILES_UPLOAD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	FILES_STATUS NUMBER DEFAULT 1 CHECK(FILES_STATUS IN (0, 1)) NOT NULL,
    FOREIGN KEY (FILES_REVIEW_NO) REFERENCES REVIEW(REVIEW_NO)
);

CREATE TABLE COMMENTS (
	COMMENTS_NO	NUMBER PRIMARY KEY,
	COMMENTS_CONTENT	VARCHAR2(4000) NULL,
	COMMENTS_INSERT	DATE DEFAULT SYSDATE NOT NULL,
	COMMENTS_UPDATE	DATE NULL,
	COMMENTS_DELETE	DATE NULL,
	COMMENTS_REVIEW_NO NUMBER NOT NULL,
	COMMENTS_MEMBER_NO	NUMBER NOT NULL,
	COMMENTS_IP	VARCHAR2(40) NULL,
    FOREIGN KEY (COMMENTS_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (COMMENTS_REVIEW_NO) REFERENCES REVIEW(REVIEW_NO)
);

CREATE TABLE LIKES(
    LIKES_NO NUMBER PRIMARY KEY,
    LIKES_MEMBER_NO NUMBER NOT NULL,
    LIKES_REVIEW_NO NUMBER NOT NULL,
    LIKES_STATUS NUMBER DEFAULT 0 CHECK(LIKES_STATUS IN (0,1)) NOT NULL,
    FOREIGN KEY (LIKES_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (LIKES_REVIEW_NO) REFERENCES REVIEW(REVIEW_NO)
);

CREATE TABLE BOARD (
	BOARD_NO	NUMBER PRIMARY KEY,
	BOARD_NAME	VARCHAR2(100) DEFAULT '이름없는 게시글' NOT NULL,
	BOARD_CONTENT	VARCHAR2(4000)		NULL,
    BOARD_ACCENT    NUMBER DEFAULT 0 NOT NULL,
	BOARD_INSERT	DATE DEFAULT SYSDATE	NOT NULL,
	BOARD_UPDATE	DATE		NULL,
	BOARD_DELETE	DATE		NULL,
	BOARD_VIEW	NUMBER	DEFAULT 0	NOT NULL,
	BOARD_IP	VARCHAR2(40)		NULL
);

CREATE TABLE CONSULTING (
    CONSULTING_NO NUMBER PRIMARY KEY,
    CONSULTING_MEMBER_NO NUMBER NOT NULL,
    FOREIGN KEY (CONSULTING_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;